### PR TITLE
Convert network code to libcurl

### PR DESCRIPTION
**Pull request by noahpistilli**
Upon request, I converted the network code to libcurl. I also cleaned up some code.

### CODE REVIEW

**Comment by noahpistilli** [comment]
Note on the error, you do need the wii-curl, wii-mbedtls and libwiisocket libraries from https://gitlab.com/4TU/wii-packages.

**Comment by KcrPL** [comment]
I'd like to test this code but I can't access my Wii for at least few weeks.

Can you test it? @larsenv

**Comment by noahpistilli** [comment]
I got Larsen to delete my Wii Number from the database multiple times, it should work perfectly fine.

**Comment by larsenv** [comment]
Thanks.

**Pull request merged**
