### PR TITLE
C++ port

### PR DESCRIPTION
**Pull request by yeah-its-gloria**
This port should resolve all the issues with the previous C version of the patcher.

It would be nice if someone could test it for me, since I don't own a Wii console. ~~I attached a compiled copy of my fork **[here](https://github.com/RiiConnect24/Mail-Patcher/files/3333267/release.zip)**.~~

Edit: I fixed a lot of stuff, and here's **[a working version](https://github.com/RiiConnect24/Mail-Patcher/files/3336902/release.zip)** of the port.

### CODE REVIEW

**Comment by Artuto** [comment]
Background: The current patcher is not compatible with CF. 

This PR should fix it, along with the C++ port.

**Comment by larsenv** [comment]
This patcher's not very happy:

image

**Comment by InternalLoss** [comment]
The patcher seems to error out with error code: 1 on my Wii - a nice blob of what I presume is the connection is also shown. (If you have a debug build of any kind that logs to a file, I can run it)

**Comment by Artuto** [comment]
Not sure how are you getting that because I just get

```
Data sent! Awaiting response... Incomplete data

Feel free to send a developer the following content:
!DOCTYPE
```

**Comment by yeah-its-gloria** [comment]
I suppose the data receiving doesn't work, I will fix that asap

**Comment by yeah-its-gloria** [comment]
I fixed the receiving code for the patcher, but I removed the broken parser. This means that it'll say that there's `Incomplete data`, but it will still print the response from the server, which is what I'd really like to see in order to verify that the receiving code works for other users too. [Here's the release.](https://github.com/RiiConnect24/Mail-Patcher/files/3340848/Mail-Patcher.zip)

**Comment by InternalLoss** [comment]
Currently, when running on my (already patched) Wii, I get thee error cd 610 back (there's no newline after the 7 in my MLID, so Wireshark shows the HTTP/1.1 as part of the same line; it's a different line on the Wii)

```
POST /cgi-bin/patcher.cgi HTTP/1.1
Host: mtw.rc24.xyz
User-Agent: Nintendo Wii

mlid=w7720650706766587HTTP/1.1 200 OK
Date: Sat, 29 Jun 2019 23:54:33 GMT
Server: Apache/2.4.25 (Debian)
Content-Length: 36
Content-Type: text/plain; charset=utf-8

cd:610
msg:Invalid Wii Friend Code.
```

I can also test on an unpatched Wii at some point, presuming I can dig one out of my room.

**Comment by yeah-its-gloria** [comment]
If the friend code is supposed to be valid, I have no idea why it actually returns `cd` as `610`.

**Comment by InternalLoss** [comment]
I found the issue!
You're not sending the Header `Content-Type: application/x-www-form-urlencoded`
Send that, and the server will correctly respond duplicate or real information.

EDIT: Also, START from a GCN pad does not correctly exit the patcher (you can run the patcher using a GCN controller from HBC, you cant exit with one though :p)

**Comment by InternalLoss** [comment]
Also, @Apfel you said that this would fix CF support, but yet AFAICT this still connects over HTTP: is that just while we're trying to debug the actual patcher working? c:

**Comment by Artuto** [comment]
I disabled HTTPS specifically because the patcher did not like it. However, it goes through CF.

**Comment by InternalLoss** [comment]
Ah, I see. That's fine c:
Lmk when a copy with the correct header exists, and I'll try it out

**Comment by yeah-its-gloria** [comment]
I just checked what the Wii actually sends to the server, and I found this:
```
2019/06/30 02:30:51 Server is online.
2019/06/30 02:31:23 New Request!
Body: <- this is actually empty
Host: mtw.rc24.xyz
Method: POST
Local Address: 192.168.178.7:56998 <- yeah I sent it to my computer, not to a server
User-Agent - [Nintendo Wii]
Content-Type - [application/x-www-form-urlencoded]
```
The body, which is supposed to contain the Mail ID as `mlid`, isn't there.

Also, this is the code for the server that I used for my `private debug` build
```go
package main

import (
	"bufio"
	"fmt"
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/cgi-bin/patcher.cgi", func(w http.ResponseWriter, r *http.Request) {
		var d []byte
		if _, err := bufio.NewReader(r.Body).Read(d); err != nil {
			log.Fatalf("an error occurred! oh noes: %s", err.Error())
		}

		log.Println("New Request!")
		fmt.Printf("Body: %s\nHost: %s\nMethod: %s\nAddress: %s\n", string(d), r.Host, r.Method, r.RemoteAddr)

		for k, v := range r.Header {
			fmt.Printf("%s - %s\n", k, v)
		}

		fmt.Fprintf(w, "here's the response, please work\r\n")
	})

	log.Println("Server is online.")
	log.Fatal(http.ListenAndServe(":80", nil))
}
```

**Comment by Artuto** [comment]
Maybe that was why we were getting CF 400 sometimes?

**Comment by yeah-its-gloria** [comment]
I have no idea, but that may be the reason - the formatting is fine, the request should work, but it just doesn't do what it's supposed to.

**Comment by InternalLoss** [comment]
I see mlid=w[WIIID] when sent in the TCP stream. Maybe just try adding that header and change nothing about the body, and I'll check it's response?

**Comment by yeah-its-gloria** [comment]
[Here you go.](https://github.com/RiiConnect24/Mail-Patcher/files/3342424/release.zip)

**Comment by InternalLoss** [comment]
Odd, that didnt seem to fix it (I mean I wasn't completely sure it would have anyways tbh)

Maybe the way the HTTP request is built is different bc C++? I wouldn't be personally sure, tbh.

Unrelated, but I also sent you an FR on Discord.

**Comment by yeah-its-gloria** [comment]
The request has been fixed, `Content-Length` was missing. ~~kill me~~
I will implement the parser now.

**Comment by Artuto** [comment]
Branch was deleted so I'm closing this. Did not work anyways.

**Pull request closed without merging**
