### PR TITLE
Fix Github Actions

### PR DESCRIPTION
**Pull request by NightScript370**
Switches to docker and uses the latest version of devkitPCC

### CODE REVIEW

**Comment by larsenv** [comment]
@NightYoshi370 Thanks so much for this, I told @KcrPL that it's hacky and unprofessional to just download a bunch of packages and such. This is much better.

So cool that we can build an app using GitHub actions!

**Comment by KcrPL** [comment]
Yup, thx.

It's not always unprofessional - what if you're building with older tools that are not compatible with the latest ones?

**Comment by NightScript370** [comment]
@larsenv No worries. I love docker and it'd be nice to have autocompilers for apps that have testers testing it.
@KcrPL You should update the app to support the latest version

**Comment by KcrPL** [comment]
In releases? We've still got some work to do.

**Comment by Peter0x44** [comment]
The mail patcher works on the latest DKP with no issues, that certainly isn't an excuse there
the times when using an older toolchain are justified are very few

**Pull request merged**
